spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://when-we-eat-chickent-2020-db.mysql.database.azure.com:3306/test?serverTimezone=UTC
    username: user@when-we-eat-chickent-2020-db
    password: ehgns5545
    hikari:
      idle-timeout: 10000
      max-lifetime: 420000
      connection-timeout: 10000
      validation-timeout: 10000

  #   local 테스트용
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: ehgns5545@

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  secret: 12345678901234567890123456789012

temp:
#로컬
  path: D:\workspace\post\data\
#  path: /app/git/spring_web_service/data/